services:
  server:
    build:
      context: ./
      dockerfile : ./dockerfiles/apache.dockerfile
    ports: 
      - 12345:80
    depends_on:
      - mysql
      - phpmyadmin
  
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  
  mongo:
    image: mongo:latest
    env_file:
      - ./env/mongo.env
    ports:
      - 27017:27017
  
  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 12346:80

  app:
    build:
      context: ./
      dockerfile: ./dockerfiles/app.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - server
