services: 
    server:
      image: nginx:stable-alpine
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - php
        - mysql
        - phpmyadmin
    php:
      build: 
        context: ./
        dockerfile: ./dockerfiles/php.dockerfile
      volumes:
        - ./src:/var/www/html:delegated
    mysql:
      image: mysql:5.7
      env_file:
        - ./env/mysql.env
      volumes:
        - ./init/:/docker-entrypoint-initdb.d

    phpmyadmin:
      image: phpmyadmin:latest
      env_file:
        - ./env/phpmyadmin.env
      ports:
        - 12346:80
      depends_on:
        - mysql

    composer:
      build:
        context: ./
        dockerfile: ./dockerfiles/composer.dockerfile
      volumes:
        - ./src:/var/www/html
    